% NDflood.m
%
% Quick probability calculation from Nate Silver's book
%
% RTB wrote it, 14 July 2019, Kinsale, Ireland; end of Cork Distance Week

% Taken from Chapter 6 of Nate Silver's "The Signal and the Noise"
%
% Heading: "The Importance of Communicating Uncertainty"
%
% "In April 1997, the Red River of the North flooded Grand Forks, North
% Dakota, overtopping the town's levees and spilling more than two miles
% into the city. Although there was no loss of life, nearly all of the
% city's 50,000 residents had to be evacuated, cleanup costs ran into the
% billions of dollars, and 75 percent of the city's homes were damaged or
% destroyed.
%
% . . . Residents of Grand Forks had been aware of the flood threat for
% months. Snowfall had been especially heavy in the Great Plains that
% winter, and the National Weather Service, anticipating runoff as the snow
% melted, had predicted the waters of the Red River would crest to
% forty-nine feet, close to the all-time record.
%
% There was just one small problem. The levees in Grand Forks had been
% built to handle a flood of fifty-one feet. Even a small miss in the
% forty-nine-foot prediction could prove catastrophic.
%
% . . . The margin of error on the Weather Service's forecast--based on how
% well their flood forecasts had done in the past--was about plus or minus
% nine feet . . . ."

%% QUESTION 1: What is the probability the water level will exceed the levee?

% Assuming what Silver is calling the "margin of error" corresponds to a
% 95% confidence interval (which is how wikipedia defines it), what is the
% probability that the water exceeded the 51-foot height of the levee?

leveeHgt = 51;  % units = feet
predHgt = 49;
CI95 = 9;       % units = feet; SD = 9/1.96
p1 = 1 - normcdf(leveeHgt,predHgt,CI95/1.96);
% ANSWER: 0.33
%
% Explanation: In order to use 'normcdf' we need to convert the confidence
% interval to a standard deviation--recall that the standard error of the
% mean is simply the standard deviation of the sampling distribution of the
% mean. You should carry around in your head the so-called "68-95-99.7
% rule," which describes the probabilty mass contained within plus-or-minus
% 1, 2 and 3 standard deviations from the mean, respectively. So a 95%
% confidence interval corresponds to about 2 standard deviates (actually,
% it's 1.96). Also recall that 'normcdf' gives us the area of the normal
% distribution less-than-or-equal-to a given value (in this case, the
% height of the levees, or 51 feet), so to find the probability of the
% water level exceeding 51 feet, we subtract the area from the total area
% of 1. We could also use:
p2 = normcdf(leveeHgt,predHgt,CI95/1.96,'upper');

%% Same calculation by simulation:

% Suppose you didn't know about 'normcdf' (or, for that matter, 'normpdf',
% but you had extensive experience with 'randn'.
nSim = 100000;
% Normal distribution with a mean of 49 and an sd of 4.6:
mySimHgts = (randn(nSim,1) .* (CI95/1.96)) + predHgt;
pSim = sum(mySimHgts > leveeHgt) / nSim;

% Plot the results of our simulation:
figure, histogram(mySimHgts);
hold on
ax = axis;
hl = line([leveeHgt,leveeHgt],[ax(3),ax(4)]);
set(hl,'Color','r');

% or can cheat and use 'normrnd'
mySimHgts = normrnd(predHgt,CI95/1.96,nSim,1);
pSim = sum(mySimHgts > leveeHgt) / nSim;

% Follow-up (Silver's book): "In fact, the river crested to fifty-four
% feet."

%% Describe the size and contents of the variable 'a' generated by the code below:
rng(1);
a = unidrnd(5,16,10000);

% Answer: 'a' will be an array with 16 rows and 10,000 columns containing
% the numbers 1-5, with equal probability.

%% Simulation approach

% Let's imagine we didn't know what 'unidrnd' (or 'np.random.randint') did.
% In fact, let's imagine that we did some kind of experiment where we took
% 16 random samples from a very large population. Maybe we measured the
% height of 16 women drawn at random from the US population. Only we then
% repeated our experiment an additional 9,999 times. So we've got 10,000
% repetitions of our experiment with a sample of size 16 for each. Now we
% make the following calculation, which will yield 10,000 values:

b  =  std(a) ./ 4;

% What would a statistician call each one of these 10,000 values?

% Answer: Standard error of the mean.

%% What would a statistician call what we have calculated and displayed below?

c = mean(a);
figure, histogram(c);

% Answer: Sampling distribution of the mean

%% What is the name for what is being calculated here?

d  =  std(c);

% Answer: Standard error of the mean.

% This is a critical realization. Once you have the sampling distribution
% of any statistic, you get the standard error of that statisic by simply
% calculating the standard deviation of the sampling distribution--no
% dividing by the sqrt of 'n'. The formula you typically use (sd / sqrt(n))
% is only a shortcut for when you want to estimate the SEM from a single
% sample. In bootstrapping, we directly estimate the entire sampling
% distribution, so all we do is take the standard deviation.

%% Final comparison

% Compare the mean of all of the 10,000 SEMs you calculated using the
% formula (stored in array 'b') with the value you calculated by taking the
% standard deviation of the sampling distribution of the mean.

% mean of the 10,000 SEMs:
disp(mean(b))

% standard deviation of the sampling distribution of the mean:
disp(d)

